-- 013: new SEO titles (meta_title) and H1s (title) for blog posts, 6 Oct 2026.
-- Source: "RTI Priority A - New Titles & H1s" (Google Sheet; tabs Priority A, B, C),
-- rows whose new title / H1 is not "Keep". Pages built from code (services,
-- locations, home ...) are changed in src/data and data/url-map.csv instead.
--
-- Run once on dev and once on live:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/013_post_titles_h1s_oct_2026.sql
-- Safe to run twice: the second run changes the same rows to the same values.
-- og_title / twitter_title follow the new title only where they still equal
-- the old one (a hand-set social title is left alone).
-- The last query lists any slug from the sheet that is not in this database.

BEGIN;

CREATE TEMP TABLE new_titles (slug text PRIMARY KEY, meta_title text NOT NULL, h1 text NOT NULL) ON COMMIT DROP;
INSERT INTO new_titles (slug, meta_title, h1) VALUES
  ($q$how-much-does-best-buy-charge-for-recycling-a-tv$q$, $q$Best Buy TV Recycling Cost (2027): Fees & Free Options$q$, $q$How Much Does Best Buy Charge to Recycle a TV?$q$),
  ($q$recycling-benefits-and-challenges$q$, $q$Recycling Pros and Cons: Benefits & Challenges (2027)$q$, $q$The Pros and Cons of Recycling$q$),
  ($q$how-to-dispose-of-lighter-fluid$q$, $q$How to Dispose of Lighter Fluid Safely (Step by Step)$q$, $q$How to Dispose of Lighter Fluid Safely$q$),
  ($q$how-to-recycle-old-iphone$q$, $q$What to Do With Old iPhones: Recycle, Trade In or Wipe$q$, $q$How to Recycle Your Old iPhone Safely$q$),
  ($q$home-depot-bulb-recycling-vs-recycle-technologies$q$, $q$Does Home Depot Recycle Fluorescent Bulbs? (2027 Answer)$q$, $q$Home Depot Bulb Recycling vs. Recycle Technologies$q$),
  ($q$appliance-recycling$q$, $q$Appliance Recycling: How to Recycle Old Appliances$q$, $q$How to Recycle Large and Small Appliances$q$),
  ($q$is-tissue-paper-recyclable-unraveling-the-truth$q$, $q$Is Tissue Paper Recyclable? The Short Answer$q$, $q$Is Tissue Paper Recyclable?$q$),
  ($q$how-to-dispose-of-broken-tv$q$, $q$How to Dispose of a Broken TV Safely and Legally$q$, $q$How to Dispose of a Broken TV$q$),
  ($q$environmentally-conscious-your-guide-to-microwave-recycling-near-you$q$, $q$Microwave Disposal Near Me: Where to Recycle It$q$, $q$Where to Recycle a Microwave Near You$q$),
  ($q$how-to-dispose-of-a-flat-screen-tv$q$, $q$How to Dispose of a Flat Screen TV (2027 Options)$q$, $q$How to Dispose of a Flat Screen TV$q$),
  ($q$uncovering-the-cons-of-recycling-and-its-impact-on-the-environment$q$, $q$Cons of Recycling: The Downsides, Explained Honestly$q$, $q$Are There Any Cons of Recycling?$q$),
  ($q$tesla-battery-recycling-secrets$q$, $q$Tesla Battery Recycling: How EV Batteries Are Recycled$q$, $q$Tesla Battery Recycling - The Secrets You Must Know$q$),
  ($q$where-to-recycle-ink-cartridges-a-comprehensive-guide$q$, $q$Where to Recycle Ink Cartridges: Stores & Mail-In$q$, $q$Where to Recycle Ink Cartridges$q$),
  ($q$are-milk-cartons-recyclable-heres-what-you-need-to-know$q$, $q$Are Milk Cartons Recyclable? What You Need to Know$q$, $q$Are Milk Cartons Recyclable?$q$),
  ($q$best-buy-tv-recycling-vs-recycle-technologies$q$, $q$Best Buy TV Recycling vs. Recycle Technologies (2027)$q$, $q$Best Buy TV Recycling vs. Recycle Technologies$q$),
  ($q$how-to-dispose-of-old-laptop$q$, $q$What to Do With an Old Laptop: Wipe, Recycle or Donate$q$, $q$How to Dispose of an Old Laptop$q$),
  ($q$itad-services-explained-secure-your-it-asset-disposal$q$, $q$IT Asset Disposal Services: Secure ITAD for Business$q$, $q$Secure IT Asset Disposal for Your Business$q$),
  ($q$what-to-do-with-old-cds$q$, $q$What to Do With Old CDs: Recycle, Reuse or Donate$q$, $q$What to Do With Old CDs - A Practical Guide$q$),
  ($q$how-to-dispose-of-old-printer-machine$q$, $q$How to Dispose of an Old Printer (Recycling Options)$q$, $q$How to Dispose of an Old Printer$q$),
  ($q$the-importance-of-air-conditioner-disposal-and-its-effects$q$, $q$Air Conditioner Disposal: How to Recycle an Old AC$q$, $q$Air Conditioner Disposal and Recycling$q$),
  ($q$household-battery-recycling-near-me-a-comprehensive-guide$q$, $q$Household Battery Recycling Near Me: Drop-Off & Mail-In$q$, $q$How to Recycle Household Batteries$q$),
  ($q$why-e-waste-recycling-in-minnesota-is-in-a-tailspin$q$, $q$Why E-Waste Recycling in Minnesota Is Struggling$q$, $q$Why E-Waste Recycling in Minnesota Is in a Tailspin$q$),
  ($q$why-choose-recycle-technologies-for-your-laptop-recycling-in-wisconsin$q$, $q$Laptop Recycling in Wisconsin: Why Choose RTI?$q$, $q$Why Choose Recycle Technologies for Laptop Recycling in Wisconsin?$q$),
  ($q$epa-enforcement-action-in-chicago-sham-recycling-alleged$q$, $q$EPA Alleges Sham Recycling in Chicago: Enforcement Action$q$, $q$EPA Enforcement Action in Chicago: Sham Recycling Alleged$q$),
  ($q$epa-enforcement-action-in-chicago-sham-recycling-alleged-2$q$, $q$EPA Chicago Sham Recycling Case (Update)$q$, $q$EPA Enforcement Action in Chicago: Sham Recycling Alleged (Update)$q$),
  ($q$why-does-recycle-technologies-offer-the-best-lamp-recycling-in-minnesota$q$, $q$Lamp Recycling in Minnesota: Why Recycle Technologies$q$, $q$Why Recycle Technologies for Lamp Recycling in Minnesota?$q$),
  ($q$lithium-battery-recycling-in-wisconsin-is-this-the-new-normal$q$, $q$Lithium Battery Recycling in Wisconsin: The New Normal$q$, $q$Lithium Battery Recycling in Wisconsin: Is This the New Normal?$q$),
  ($q$epa-awards-over-7-million-to-indiana-university$q$, $q$EPA Awards $7M to Indiana University for Great Lakes$q$, $q$EPA Awards Over $7 Million to Indiana University to Safeguard the Great Lakes$q$),
  ($q$why-does-the-future-of-electronic-waste-disposal-rest-on-our-shoulders$q$, $q$Does the Future of E-Waste Disposal Rest on Us?$q$, $q$Why Does The Future of Electronic Waste Disposal Rest on our Shoulders?$q$),
  ($q$how-recycling-practices-can-lead-to-environmental-sustainability$q$, $q$How Recycling Leads to Environmental Sustainability$q$, $q$Explain How Recycling Practices Can Lead to Environmental Sustainability$q$),
  ($q$why-it-is-illegal-to-throw-away-electronics-why-does-electronics-recycling-matter$q$, $q$Why It Is Illegal To Throw Away Electronics?$q$, $q$Why It Is Illegal To Throw Away Electronics? Why does Electronics Recycling matter?$q$),
  ($q$battery-recycling-and-recycle-techn$q$, $q$Battery Recycling: What to Expect$q$, $q$Battery Recycling and Recycle Technologies? What to expect?$q$),
  ($q$how-to-dispose-small-appliances-safely-and-responsibly$q$, $q$How to Dispose Small Appliances Safely and Responsibly$q$, $q$How to Dispose Small Appliances Safely and Responsibly$q$),
  ($q$is-aluminum-foil-recyclable-unwrapping-the-myths-and-facts$q$, $q$Is Aluminum Foil Recyclable? Unwrapping the Myths and Facts$q$, $q$Is Aluminum Foil Recyclable? Unwrapping the Myths and Facts$q$),
  ($q$florida-fluorescent-bulb-recycling-regulations$q$, $q$Florida Fluorescent Bulb Recycling Regulations$q$, $q$Florida Fluorescent Bulb Recycling Regulations$q$),
  ($q$why-is-recycling-a-computer-important$q$, $q$Why Recycling Computer Parts Is Important$q$, $q$Why is Recycling Computer Parts is Important?$q$),
  ($q$how-to-dispose-of-oil-safely-and-responsibly$q$, $q$How to Dispose of Oil Safely and Responsibly$q$, $q$How to Dispose of Oil Safely and Responsibly$q$),
  ($q$reliable-recycling-centers-in-woodbury-an-easy-solution-for-citizens$q$, $q$Recycling centre in Woodbury & surrounding$q$, $q$Reliable Recycling Centers In WoodBury: An Easy Solution For Citizens$q$),
  ($q$what-to-do-with-a-dead-graphic-card-should-i-recycle-it-or-not$q$, $q$Dead Graphics Card: Recycle It or Not?$q$, $q$What To Do With a Dead Graphic Card, Should I Recycle It or Not?$q$),
  ($q$lithium-ion-battery-disposal$q$, $q$Safe Lithium-Ion Battery Disposal: Prevent Fires$q$, $q$Strategies for Safe Lithium-ion Battery Disposal To Prevent Fires$q$),
  ($q$dispose-of-fire-extinguisher$q$, $q$How to Dispose of Fire Extinguisher Properly$q$, $q$How to Dispose of Fire Extinguisher Properly$q$),
  ($q$how-to-dispose-of-washer-and-dryer-a-complete-guide$q$, $q$How to Dispose of Washer and Dryer: A Complete Guide$q$, $q$How to Dispose of Washer and Dryer: A Complete Guide$q$),
  ($q$tesla-wall-battery-recycling-unveiled-on-2024-earth-day$q$, $q$Tesla Wall Battery Recycling Unveiled On 2025 Earth Day$q$, $q$Tesla Wall Battery Recycling Unveiled On 2025 Earth Day$q$),
  ($q$is-glass-recyclable-understanding-the-benefits-and-challenges$q$, $q$Is Glass Recyclable? Benefits and Challenges$q$, $q$Is Glass Recyclable? Understanding the Benefits and Challenges with Recycle Technologies$q$),
  ($q$effortless-recycling-in-minnetonka-recycle-technologies-flexible-e-waste-recycling-services$q$, $q$Recycling centre in Minnetonka & surrounding$q$, $q$Effortless Recycling in Minnetonka: Recycle Technologies’ Flexible E-Waste Recycling Services$q$),
  ($q$recycling-technologies-in-bloomington-all-what-you-need-to-know$q$, $q$Recycling centre in Bloomington & surrounding$q$, $q$Recycling Technologies in Bloomington: All What You Need to Know$q$),
  ($q$the-power-of-car-battery-recycling$q$, $q$What are the Benefits of Car Battery Recycling$q$, $q$What are the Benefits of Car Battery Recycling & Why Should You Consider It?$q$),
  ($q$battery-recycling-in-bloomington-minnesota$q$, $q$Battery Recycling Bloomington, Minnesota$q$, $q$Battery Recycling in Bloomington, Minnesota$q$),
  ($q$best-buy-recycling-company-recycletechnology-choose-wisely$q$, $q$Recycle Technologies vs Best Buy Recycling$q$, $q$Recycle Technologies Vs. Best Buy Recycling Company: Your Best Bet For Computer Recycling$q$),
  ($q$e-waste-recycling-ups-drop-box-vs-recycle-technologies$q$, $q$E-Waste Recycling: UPS Drop Box vs. Recycle Technologies$q$, $q$Navigating E-Waste Recycling: UPS Drop Box vs. Recycle Technologies$q$),
  ($q$electronics-recycling-near-me-recycle-technologies-services$q$, $q$Electronics Recycling Near Me: Our Services$q$, $q$Electronics Recycling Near Me: Comprehensive E-Waste Solutions By Recycle Technologies$q$),
  ($q$can-you-recycle-styrofoam-understanding-the-challenges-and-alternatives$q$, $q$Can You Recycle Styrofoam? Challenges & Alternatives$q$, $q$Can You Recycle Styrofoam? Understanding the Challenges and Alternatives$q$),
  ($q$how-to-recycle-responsibly-in-benton-county$q$, $q$Recycling centre in Benton County & surrounding$q$, $q$How to Recycle Responsibly in Benton County$q$),
  ($q$hp-laptop-battery-recycling$q$, $q$HP Laptop Battery Recycling: Why It Matters$q$, $q$HP laptop battery recycling: Proper way to dispose of your e-waste$q$),
  ($q$clean-earth-camp-lejeune$q$, $q$Clean Earth Camp Lejeune: Awareness for a Cleaner Future$q$, $q$Clean Earth Camp Lejeune Generates Awareness For a Cleaner Environment and Sets Goals For a Sustainable Future$q$),
  ($q$embracing-a-greener-tomorrow-recycling-electronics-responsibly-in-blaine-mn$q$, $q$Recycling centre in Blaine & surrounding$q$, $q$Embracing a Greener Tomorrow: Recycling Electronics Responsibly in Blaine, MN$q$),
  ($q$recycle-responsibly-your-guide-to-recycle-technologiess-facilities-for-wisconsin-residents$q$, $q$Recycling centre in Wisconsin & surrounding$q$, $q$Recycle Responsibly: Your Guide to Recycle Technologies’s Facilities for Wisconsin Residents$q$),
  ($q$innovative-ways-our-light-bulb-recycling-kit-can-refine-sustainability$q$, $q$Light Bulb Recycling Kit: How It Boosts Sustainability$q$, $q$Innovative Ways Our Light Bulb Recycling Kit Can Refine Sustainability$q$),
  ($q$exploring-the-positive-effects-of-e-waste-recycling$q$, $q$Exploring The Positive Effects of E-Waste Recycling$q$, $q$Tech Trash to Green Gold: Exploring the Positive Effects of Recycling E-Waste$q$),
  ($q$tesla-powerwall-recycling-on-earth-day$q$, $q$Tesla Powerwall Recycling on Earth Day 2024$q$, $q$Sustainable Future: Tesla Powerwall Recycling on Earth Day 2024$q$),
  ($q$recycle-technologies-plymouths-cutting-edge-recycling-center$q$, $q$Recycling centre in Plymouth & surrounding$q$, $q$Recycle Technologies: Plymouth’s Cutting-Edge  Recycling Center$q$),
  ($q$fluorescent-tube-disposal-kits-through-mail-in-recycling-service$q$, $q$Fluorescent Tube Disposal Kits by Mail$q$, $q$Fluorescent Tube Disposal Kits through Mail-in Recycling Service$q$),
  ($q$unveiling-the-hidden-side-the-disadvantages-of-recycling-explained$q$, $q$The Disadvantages of Recycling Explained$q$, $q$Unveiling the Hidden Side: The Disadvantages of Recycling Explained$q$),
  ($q$empower-your-community-with-recycle-technologies-comprehensive-recycling-services-in-milwaukee$q$, $q$Recycling centre in Milwaukee & surrounding$q$, $q$Empower Your Community with Recycle Technologies: Comprehensive Recycling Services in Milwaukee$q$),
  ($q$eco-friendly-solutions-led-bulb-recycling-near-me$q$, $q$Eco-Friendly Solutions: LED Bulb recycling Near Me$q$, $q$LED Bulb Recycling Near Me: Reducing Waste and Protecting the Environment$q$),
  ($q$phase-out-your-fluorescent-light-bulbs-with-recycle-technologies$q$, $q$Phase Out Fluorescent Light Bulbs$q$, $q$A New Era: Phase Out Your Fluorescent Light Bulbs with Recycle Technologies$q$),
  ($q$which-is-the-best-tv-recycling-near-me$q$, $q$Which Is The Best TV Recycling Near Me?$q$, $q$Which is the Best TV Recycling Near Me?$q$),
  ($q$how-to-dispose-of-batteries-responsibly$q$, $q$How to Dispose of Batteries responsibly?$q$, $q$How to Dispose of Batteries responsibly?$q$),
  ($q$home-depot-banned-products$q$, $q$Home Depot Fined $1.6M for Selling Banned Products$q$, $q$Home Depot Fined $1.6 Million for Selling Banned Products Despite Compliance Measures$q$),
  ($q$reliable-ev-battery-recycling-companies$q$, $q$Reliable EV Battery Recycling Companies$q$, $q$Reliable EV Battery Recycling Companies$q$),
  ($q$effortless-waste-management-best-way-disposal-revealed$q$, $q$Effortless Waste Management: Best Way Disposal Revealed$q$, $q$Effortless Waste Management: Best Way Disposal Revealed$q$),
  ($q$secure-it-asset-disposition-services-near-me-as-a-business-owner$q$, $q$Secure IT Asset Disposition for Business Owners$q$, $q$Recycle Technologies: Leading The Charge In Secure IT Asset Disposition Services Near Me$q$),
  ($q$how-recycle-technologies-is-elevating-e-waste-management-in-brooklyn-park$q$, $q$Recycling centre in BrookLyn Park & surrounding$q$, $q$How Recycle Technologies Is Elevating E-Waste Management in Brooklyn Park$q$),
  ($q$why-is-tv-recycling-preferable-choice-to-minimize-ecological-footprint$q$, $q$TV Recycling: Minimize Your Ecological Footprint$q$, $q$Why is TV Recycling Preferable Choice To Minimize Ecological Footprint$q$),
  ($q$hard-drive-shredding-3-ways-it-helps-with-it-asset-disposition$q$, $q$Hard Drive Shredding: 3 Ways It Helps ITAD$q$, $q$Hard Drive Shredding 3 Ways It Helps with IT Asset Disposition$q$),
  ($q$best-buy-geek-squad-vs-recycle-technologies$q$, $q$Best Buy Geek Squad vs. Recycle Technologies$q$, $q$Best Buy Geek Squad vs. Recycle Technologies: Who's Better at Promoting  Circular Economy (on page)$q$),
  ($q$what-is-the-process-of-electronic-recycling$q$, $q$What Is the Process of Electronic Recycling?$q$, $q$What is the process of Electronic Recycling?$q$),
  ($q$recycling-leading-the-way-in-sustainable-waste-management$q$, $q$Top Recycling Companies Leading Sustainable Waste Management$q$, $q$Top Companies in Recycling: Leading the Way in Sustainable Waste Management$q$),
  ($q$from-pilot-to-permanent-albertas-electronics-recycling-program-expands$q$, $q$Alberta's Electronics Recycling Program Expands$q$, $q$From Pilot to Permanent: Alberta's Electronics Recycling Program Expands$q$),
  ($q$e-waste-7-things-that-are-recyclable$q$, $q$7 Recyclable Things You Never Knew About$q$, $q$Seven Things That Are Recyclable Which You Never Knew They Weren't$q$),
  ($q$recycle-technologies-spotlight-electronic-recycling-in-ramsey$q$, $q$Recycling centre in Ramsey & surrounding$q$, $q$Recycle Technologies Spotlight: Electronic Recycling in Ramsey$q$),
  ($q$a-review-of-recycle-technologies-services-for-businesses-in-minneapolis$q$, $q$Recycling centre in Minneapolis & surrounding$q$, $q$A Review of Recycle Technologies Services For Businesses in Minneapolis$q$),
  ($q$fire-breaks-out-at-midtown-manhattan-e-bike-shop$q$, $q$E-Bike Shop Fire in Midtown Manhattan Injures Firefighter$q$, $q$Fire Breaks Out at Midtown Manhattan E-Bike Shop, Firefighter Injured$q$),
  ($q$recycle-technologies-empowers-lakeville-for-a-better-future$q$, $q$Recycling centre in LakeVille & surrounding$q$, $q$Recycle Technologies Empowers Lakeville for a Better Future$q$),
  ($q$how-businesses-in-east-bethel-are-embracing-recycling$q$, $q$Recycling centre in East Bethel & surrounding$q$, $q$How Businesses in East Bethel Are Embracing Recycling$q$),
  ($q$electronic-recycle-provides-environmental-opportunities$q$, $q$Electronic Recycle Provides Environmental Opportunities$q$, $q$Electronic Recycle Provides Environmental Opportunities$q$),
  ($q$united-states-environmental-protection-agency-news$q$, $q$EPA: Lipari Landfill Cleanup, Alcyon Lake Restoration$q$, $q$United States Environmental Protection Agency Declares Lipari Landfill Cleanup Complete, Highlights Alcyon Lake Restoration$q$),
  ($q$why-recycling-batteries-is-important-if-we-want-to-reduce-our-carbon-footprint$q$, $q$Reduce Your Carbon Footprint with Battery Recycling$q$, $q$Why Recycling batteries is important if we want to reduce our carbon footprint?$q$),
  ($q$why-recycle-technologies-is-best-for-tesla-battery-recycling$q$, $q$Why Recycle Technologies for Tesla Battery Recycling$q$, $q$Why Recycle Technologies Is The Best Choice for Tesla Battery Recycling$q$),
  ($q$effective-it-asset-disposition-strategies$q$, $q$Effective IT Asset Disposition (ITAD) Strategies$q$, $q$Implementing Effective IT Asset Disposition (ITAD) Strategies for a Seamless Transition$q$),
  ($q$sham-lighting-recyclers-are-you-at-risk$q$, $q$Sham Lighting Recyclers –Are You At Risk?$q$, $q$Sham Lighting Recyclers – Are You At Risk$q$),
  ($q$recycling-revolution-how-schools-go-green-in-back-to-school$q$, $q$How Schools Can Go Green This Back-to-School Season$q$, $q$Recycling Revolution: How Schools Can Go Green This Back-to-School Season$q$),
  ($q$your-guide-on-how-to-dispose-big-appliances-efficiently$q$, $q$Your Guide on How to Dispose Big Appliances Efficiently$q$, $q$Your Guide on How to Dispose Big Appliances Efficiently$q$),
  ($q$year-in-review-2023-e-waste-recycling-news-that-amazed-us-part-2-of-4$q$, $q$E-Waste Recycling News: 2023 Year in Review$q$, $q$Year in Review 2023: E-waste Recycling News that Amazed Us (Part 2 of 4)$q$),
  ($q$from-waste-to-resource-benefits-business-can-reap-from-recycling-centers-in-st-paul$q$, $q$Recycling centre in St Paul & surrounding$q$, $q$From Waste to Resource: Benefits Business Can Reap From Recycling Centers in St. Paul$q$),
  ($q$usa-recycling-paves-the-way-for-a-greener-future-on-earth-day-2024$q$, $q$Earth Day: USA Recycling for a Greener Future$q$, $q$USA Recycling Paves the Way for a Greener Future on Earth Day 2024$q$),
  ($q$recycle-technologies-busts-top-5-battery-recycling-myths-in-appleton$q$, $q$Top 5 Battery Recycling Myths Busted (Appleton)$q$, $q$Recycle Technologies Busts Top 5 Battery Recycling Myths In Appleton$q$),
  ($q$e-scrap-processor-charged-with-illegal-dumping$q$, $q$E-scrap Processor Charged With Illegal Dumping$q$, $q$E-scrap processor charged with illegal dumping$q$),
  ($q$challenges-with-e-cigarette-waste-amid-safe-disposal-shortage$q$, $q$E-Cigarette Waste: Disposal Challenges & Shortages$q$, $q$Young Users Face Challenges with E-Cigarette Waste Amid Safe Disposal Shortage$q$),
  ($q$why-does-battery-recycling-matter-what-are-the-benefits-of-battery-recycling$q$, $q$Why Battery Recycling Matters: Key Benefits$q$, $q$Why does battery recycling matter? What are the benefits of battery recycling?$q$),
  ($q$argonne-national-laboratory-strives-to-reduce-e-waste-through-biodegradable-luminescent-polymers$q$, $q$Argonne Lab Fights E-Waste with Biodegradable Polymers$q$, $q$Argonne National Laboratory Strives To Reduce E-Waste Through Biodegradable Luminescent Polymers$q$),
  ($q$why-e-waste-recycling-is-the-only-solution-to-this-toxic-crisis$q$, $q$E-Waste Recycling: The Answer to the Toxic Crisis$q$, $q$Why E-waste Recycling Is the Only Solution to this Toxic Crisis?$q$),
  ($q$why-there-is-a-need-for-better-strategies-for-e-waste-recycling$q$, $q$Why E-Waste Recycling Needs Better Strategies$q$, $q$Why There Is A Need for Better Strategies for E-waste Recycling$q$),
  ($q$national-drinking-water-standard-to-protect-100m-people-from-pfas-pollution$q$, $q$EPA's First National Drinking Water Standard for PFAS$q$, $q$EPA Sets First National Drinking Water Standard to Protect 100 Million People from PFAS Exposure$q$),
  ($q$how-did-we-get-paper-shredding-so-wrong-can-we-make-it-better$q$, $q$How Did We Get Paper Shredding So Wrong?$q$, $q$How Did We Get Paper Shredding So Wrong? Can We Make It Better?$q$),
  ($q$why-chemical-recycling-is-a-bad-call-for-resolving-our-electronic-waste-problem$q$, $q$Why Chemical Recycling Is a Bad Call for E-Waste$q$, $q$Why Chemical Recycling is a Bad Call For Resolving Our Electronic Waste Problem?$q$),
  ($q$year-in-review-2023-e-waste-recycling-news-that-amazed-us-part-4$q$, $q$2023 E-Waste News That Amazed Us (Part 4 of 4)$q$, $q$Year in Review 2023: E-waste Recycling News that Amazed Us (Part 4 of 4)$q$),
  ($q$social-responsibility-recycling$q$, $q$Business Social Responsibility and Recycling$q$, $q$Why Social Responsibility of Business and Recycling are important?$q$),
  ($q$how-recycle-technologies-is-boosting-e-waste-recycling-in-st-cloud$q$, $q$Recycling centre in St Cloud & surrounding$q$, $q$How Recycle Technologies is Boosting E-Waste Recycling in St Cloud$q$),
  ($q$recycling-near-me-the-best-choice-for-business-e-waste$q$, $q$Recycling Near Me: The Best Choice for Business E-Waste$q$, $q$Recycling Near Me: The Best Choice for Business E-Waste$q$),
  ($q$drinking-water-warning-issued-nationwide$q$, $q$Drinking Water Warning Issued Nationwide!$q$, $q$Drinking Water Warning Issued Nationwide!$q$),
  ($q$year-in-review-2023-e-waste-recycling-news-that-amazed-us-part-3-of-4$q$, $q$2023 E-Waste News That Amazed Us (Part 3 of 4)$q$, $q$Year in Review 2023: E-waste Recycling News that Amazed Us (Part 3 of 4)$q$),
  ($q$how-recycle-technologies-is-leading-the-way-in-washington-county$q$, $q$Recycling centre in Washington County & surrounding$q$, $q$How Recycle Technologies is Leading the Way in Washington County$q$),
  ($q$university-graz-launches-battery-recycling-initiative$q$, $q$University of Graz Launches New Battery Recycling Initiative$q$, $q$University of Graz Launches New Battery Recycling Initiative$q$),
  ($q$burnsvilles-sustainable-recycling-revolution-with-recycle-technologies$q$, $q$Recycling centre in BurnsVille & surrounding$q$, $q$Burnsville's Sustainable Recycling Revolution with Recycle Technologies$q$),
  ($q$anoka-countys-sustainable-future-recycle-technologies-role-in-electronic-waste-recycling$q$, $q$Recycling centre in Anoka County & surrounding$q$, $q$Anoka County's Sustainable Future: Recycle Technologies’ Role in Electronic Waste Recycling$q$),
  ($q$why-electronic-waste-disposal-is-the-culprit-for-growing-e-waste$q$, $q$E-Waste Disposal: The Culprit Behind Growing E-Waste$q$, $q$Why electronic waste disposal is the culprit for growing e-waste$q$),
  ($q$whom-to-trust-if-i-want-to-recycle-my-phone$q$, $q$Whom To Trust If I Want to Recycle My Phone?$q$, $q$Whom To Trust If I Want to Recycle My Phone?$q$),
  ($q$how-recycle-technologies-promotes-sustainability-for-coon-rapids-residents$q$, $q$Recycling centre in Coon Rapids & surrounding$q$, $q$How Recycle Technologies Promotes Sustainability for Coon Rapids Residents$q$),
  ($q$how-to-lessen-our-carbon-footprint-with-electronic-waste-recycling$q$, $q$Lessen Your Carbon Footprint with E-Waste Recycling$q$, $q$How To Lessen Our Carbon Footprint With Electronic Waste Recycling?$q$),
  ($q$epa-and-white-house-honor-environmental-leaders-with-prestigious-awards$q$, $q$EPA & White House Honor Environmental Leaders$q$, $q$EPA and White House Honor Environmental Leaders with Prestigious Awards$q$),
  ($q$recycle-technologies-pioneering-green-innovations-in-edina$q$, $q$Recycling centre in Edina & surrounding$q$, $q$Recycle Technologies: Pioneering Green Innovations in Edina$q$),
  ($q$massachusetts-based-lt-governor-kim-driscoll-bags-the-recycling-impact-award-2024$q$, $q$Lt. Governor Kim Driscoll Wins 2024 Recycling Impact Award$q$, $q$Massachusetts Based Lt. Governor Kim Driscoll Bags The “Recycling Impact Award” 2024$q$),
  ($q$e-waste-recycling-news-you-may-have-missed-october-edition$q$, $q$E-Waste Recycling News: October Edition$q$, $q$E-waste Recycling News You May Have Missed October Edition$q$),
  ($q$document-destruction-services-and-its-importance-in-todays-world$q$, $q$Document Destruction Services and Why They Matter$q$, $q$Document Destruction Services And Its Importance in Today’s World$q$),
  ($q$promoting-sustainable-practices-recycling-in-scott-county-with-recycle-technologies$q$, $q$Recycling centre in Scott County & surrounding$q$, $q$Promoting Sustainable Practices: Recycling in Scott County with Recycle Technologies$q$),
  ($q$declutter-your-home-get-rid-of-large-junk-items-with-recycle-technologies$q$, $q$Declutter Your Home: Get Rid of Large Junk Items$q$, $q$Declutter your home: Get rid of Large Junk items with Recycle Technologies$q$),
  ($q$rhode-island-solar-energy$q$, $q$Rhode Island's New Energy Storage Act Boosts Solar$q$, $q$Rhode Island Solar Energy is Advanced With New Energy Storage Act$q$),
  ($q$top-reasons-to-choose-recycle-technologies-for-e-waste-recycling-in-racine$q$, $q$Recycling centre in Racine & surrounding$q$, $q$Top Reasons to Choose Recycle Technologies for E-Waste Recycling in Racine$q$),
  ($q$on-transforming-recycling-solutions-in-olmsted-county$q$, $q$Recycling centre in Olmsted County & surrounding$q$, $q$On Transforming Recycling Solutions in Olmsted County$q$),
  ($q$recycle-smarter-in-dakota-county-solution-from-recycle-technologies$q$, $q$Recycling centre in Dakota County & surrounding$q$, $q$Recycle Smarter in Dakota County: Solution from Recycle Technologies$q$);

UPDATE posts p SET
  og_title      = CASE WHEN p.og_title = p.meta_title THEN n.meta_title ELSE p.og_title END,
  twitter_title = CASE WHEN p.twitter_title = p.meta_title THEN n.meta_title ELSE p.twitter_title END,
  meta_title    = n.meta_title,
  title         = n.h1,
  updated_at    = now()
FROM new_titles n
WHERE p.slug = n.slug
  AND (p.meta_title IS DISTINCT FROM n.meta_title OR p.title IS DISTINCT FROM n.h1);

SELECT count(*) AS posts_now_matching_sheet
  FROM posts p JOIN new_titles n ON n.slug = p.slug
 WHERE p.meta_title = n.meta_title AND p.title = n.h1;

SELECT n.slug AS not_in_this_database
  FROM new_titles n LEFT JOIN posts p ON p.slug = n.slug
 WHERE p.id IS NULL;

COMMIT;
